name: Java CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 1.17
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17.0.12

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4

    - name: Build with Gradle
      run: ./gradlew build -x spotlessCheck

  format:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 1.17
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17.0.8

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4

    - name: Check code format
      run: ./gradlew spotlessCheck
